hepsi: derle calistir 


derle:
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp 
	g++ -I ./include/ -o ./lib/List.o -c ./src/List.cpp 
	g++ -I ./include/ -o ./lib/Func.o -c ./src/Func.cpp 
	g++ -I ./include -o ./bin/test.exe ./lib/Node.o ./lib/List.o ./lib/Func.o ./src/test.cpp

calistir:
	bin/test
